[default]
# Dev mode
DEBUG = false
# Pathes
DB_PATH = 'data/db'
LOG_PATH = 'logs/bot.log'
# Internal parameters
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
# Notification message
TIMEZONE = 'US/Eastern'
ADMINS = [ '@PLACEHOLDER' ]

[production]
DEBUG = false
TOKEN = 'SECRET_PLACEHOLDER'
CHANNEL_USERNAME = 'PLACEHOLDER'
CHAT_ID = 'PLACEHOLDER'
CONVERSATION_TIMEOUT = 86400            # 24 hours (in seconds)

[development]
DEBUG = true
TOKEN = 'SECRET_PLACEHOLDER'
CHANNEL_USERNAME = 'PLACEHOLDER'
CHAT_ID = 'PLACEHOLDER'
CONVERSATION_TIMEOUT = 10               # 10 seconds